config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'products#index'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'checkout/create' => 'checkout#create', as: 'checkout_create'

  post 'cart_items' => 'cart_items#create'
  get 'cart_items/:id' => 'cart_items#show', as: 'cart_item'
  delete 'cart_items/:id' => 'cart_items#destroy'

  get 'checkout_success', to: 'checkout#checkout_success'

  resources :products do
    resources :comments
    collection do
      match 'search' => 'products#search', via: %i[get post], as: :search
    end
  end

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show]
    end
  end

  get '*path' => redirect('/')
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :content, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_product
  before_action :set_comment, except: %i[create]

  def create
    @comment = @product.comments.build(comment_params)
    @comment.user = current_user

    if @product.save
      flash[:notice] = 'Comment created successfully!'
    else
      flash[:alert] = 'Comment not created!'
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Comment has been updated'
    else
      flash[:alert] = 'Comment was not updated!'
    end
    redirect_to product_path(@product)
  end

  def destroy
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:product_id, :content)
  end

  def set_product
    @product = Product.find_by(id: params[:product_id])
  end

  def set_comment
    @comment = @product.comments.find_by(id: params[:id])
  end
end

app/views/comments/_comment.html.erb
<div id= "comment-<%= comment.id %>">
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong><%= comment.user.name %></strong>
      [<%= comment.created_at.strftime("%I:%M%P") %>]
    </div>
    <div class="panel-body">
      <%= comment.content %>
      <% if comment.user_id == current_user.id %>
        <br><br>
        <div class="btn-group">
          <div style="display:flex">
            <div>
              <%= link_to "Delete", product_comment_path(@product, comment), method: :delete, remote: true, style: 'float: right', class:"btn btn-sm btn-danger"%>
            </div>
            <div style="margin-left:5px">
              <%= link_to "Edit", edit_product_comment_path(@product,comment), style: 'float: right', class:"btn btn-sm btn-warning" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Add a comment:</h2>
  </div>
  <div class="panel-body">
    <%= form_with model: @comment, url: product_comments_path(params[:id]), method: :post  do |form| %>
      <%= render 'shared/error_messages',resource: @comment %>
      <div class="field form-group">
        <%= form.text_area :content, autocomplete: "content", class: "form-control", placeholder: "Add a comment" %>
      </div>
      <div class="actions">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Add a comment:</h2>
  </div>
  <div class="panel-body">
    <%= form_with model: @comment, url: product_comments_path(params[:id]), method: :post  do |form| %>
      <%= render 'shared/error_messages',resource: @comment %>
      <div class="field form-group">
        <%= form.text_area :content, autocomplete: "content", class: "form-control", placeholder: "Add a comment" %>
      </div>
      <div class="actions">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/create.js.erb
$('#comment_pane').prepend("<%= j render @comment %>");
$('#comment_body').val('');

app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').html('');

app/views/comments/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Add a comment:</h2>
  </div>
  <div class="panel-body">
    <%= simple_form_for([@product, @comment], remote: true) do |form| %>​
      <%= render 'shared/error_messages',resource: @comment %>
      <div class="field form-group">
        <%= form.text_area :content, autocomplete: "content", class: "form-control", placeholder: "Add a comment" %>
      </div>
      <div class="actions">
        <%= form.button :submit, label: 'Add Comment', class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/update.js.erb
$('#comments').append("<%= j render @comment %>");