config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'products#index'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'checkout/create' => 'checkout#create', as: 'checkout_create'

  post 'cart_items' => 'cart_items#create'
  get 'cart_items/:id' => 'cart_items#show', as: 'cart_item'
  delete 'cart_items/:id' => 'cart_items#destroy'

  get 'checkout_success', to: 'checkout#checkout_success'

  resources :products do
    resources :comments
    collection do
      match 'search' => 'products#search', via: %i[get post], as: :search
    end
  end

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show]
    end
  end

  get '*path' => redirect('/')
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </strong>
    <% resource.errors.full_messages.each do |message| %>
      <div>
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <strong>
        <%= link_to 'E-Commerece', root_path, class:"navbar-brand" %>
      </strong>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li class="active">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li>
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
        <li>
          <%= link_to 'Sell Product', new_product_path, class:"nav-link" %>
        </li>
        <% else %>
          <li class="active">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li>
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        <li>
          <%= link_to 'Buy Products', products_path, class:"nav-link" %>
        </li>
        <li>
          <%= link_to '<span class="glyphicon glyphicon-shopping-cart"> </span>'.html_safe, cart_path(@current_cart), class:"nav-link" %>
        </li>
      </ul>
      <div class="navbar-form navbar-right">
        <%= search_form_for @search, url: search_products_path, html: { method: :post } do |f| %>
          <div class="field form-group">
            <%= f.text_field :name_cont, class: "form-control", placeholder: "Name contains" %>
          </div>
          <%= f.submit "Search", class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>