config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'products#index'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'checkout/create' => 'checkout#create', as: 'checkout_create'

  post 'cart_items' => 'cart_items#create'
  get 'cart_items/:id' => 'cart_items#show', as: 'cart_item'
  delete 'cart_items/:id' => 'cart_items#destroy'

  get 'checkout_success', to: 'checkout#checkout_success'

  resources :products do
    resources :comments
    collection do
      match 'search' => 'products#search', via: %i[get post], as: :search
    end
  end

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show]
    end
  end

  get '*path' => redirect('/')
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user, optional: true

  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :set_cart, only: %i[show]
  before_action :set_cart_to_delete, only: %i[destroy]
  before_action :authenticate_user!, except: [:show]
  before_action :set_cart_user, only: [:show]

  def show; end

  def destroy
    if @cart.destroy
      flash[:notice] = 'Cart deleted successfully!'
    else
      flash[:alert] = 'Cart not deleted!.'
    end

    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private

  def set_cart_to_delete
    @cart = Cart.find(params[:id])
  end

  def set_cart
    @cart = @current_cart
  end

  def set_cart_user
    @current_cart.user = current_user unless current_user.nil?
    @current_cart.save
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  def total_bill(cart)
    coupon = Coupon.find_by(user_id: cart.user_id)
    sum = 0

    cart.cart_items.each { |cart_item| sum += cart_item.product.price * cart_item.quantity }
    
    return sum - (sum * discount(coupon)) unless coupon.nil? || coupon_valid_till(coupon) < DateTime.now

    sum
  end

  def discount(coupon)
    coupon.discount_percentage
  end

  def coupon_valid_till(coupon)
    coupon.valid_till
  end
end

app/views/carts/show.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    <div class="panel-title">
      <div class="row">
        <div class="col-xs-6">
          <h5><span class="glyphicon glyphicon-shopping-cart"></span> Shopping Cart</h5>
        </div>
        <div class="col-xs-6">
          <%= link_to 'Continue shopping', products_path, class: 'btn btn-primary btn-sm btn-block' %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <% @cart.cart_items.each do |cart_item| %>
      <div class="row">
        <div class="col-xs-2">
          <img class="img-responsive" src="">
        </div>
        <div class="col-xs-4">
          <h4 class="product-name">
            <strong><%= cart_item.product.name %></strong>
          </h4>
          <h4>
            <small><%= cart_item.product.description %></small>
          </h4>
        </div>
        <div class="col-xs-6">
          <div class="col-xs-6 text-right">
            <h6><strong><%= number_to_currency(cart_item.product.price) %> <span class="text-muted">x</span></strong></h6>
          </div>
          <div class="col-xs-4">
            <h6><strong><%= cart_item.quantity %></strong></h6>
          </div>
          <div class="col-xs-2">
            <%= link_to '<span class="glyphicon glyphicon-trash"> </span>'.html_safe, cart_item_path(cart_item), method: :delete %>
          </div>
        </div>
      </div>
      <hr>
    <% end %>
    <div class="row">
      <div class="text-center">
        <div class="col-xs-9">
          <h6 class="text-right">Added items?</h6>
        </div>
        <div class="col-xs-3">
          <%= link_to 'Update cart', cart_path(@current_cart), class:"btn btn-default btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-footer">
    <div class="row text-center">
      <div class="col-xs-9">
        <h4 class="text-right">Total <strong><%= number_to_currency(total_bill(@cart)) %></strong></h4>
      </div>
      <div class="col-xs-3">
        <%= button_to "Checkout", checkout_create_path, params: {:cart_id => @cart.id }, remote: true, class:'btn btn-success btn-block' %>
      </div>
    </div>
  </div>
</div>