config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'products#index'

  get 'carts/:id' => 'carts#show', as: 'cart'
  delete 'carts/:id' => 'carts#destroy'

  post 'checkout/create' => 'checkout#create', as: 'checkout_create'

  post 'cart_items' => 'cart_items#create'
  get 'cart_items/:id' => 'cart_items#show', as: 'cart_item'
  delete 'cart_items/:id' => 'cart_items#destroy'

  get 'checkout_success', to: 'checkout#checkout_success'

  resources :products do
    resources :comments
    collection do
      match 'search' => 'products#search', via: %i[get post], as: :search
    end
  end

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :products, only: [:index, :show]
    end
  end

  get '*path' => redirect('/')
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :user

  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items

  validates :name, :price, :description, presence: true
  validates :name, uniqueness: true
end

app/controllers/api/v1/products_controller.rb
module Api
  module V1
    class ProductsController < ApiController
      def index
        @products = Product.all
        render json: @products
      end

      def show
        @product = Product.find(params[:id])
        render json: @product
      end
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  # before_action :authenticate_user!, except: [:index]

  def index
    @search = Product.search(params[:q])
    @products = @search.result
  end

  def show
    @comments = @product.comments.includes(:user).all
    @comment  = @product.comments.build
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to @product
      flash[:notice] = 'Product was successfully created.'
    else
      flash[:alert] = 'Product was not created.'
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product
      flash[:notice] = 'Product was successfully updated.'
    else
      flash[:alert] = 'Product was not updated.'
    end
  end

  def destroy
    if @product.destroy
      redirect_to products_url
      flash[:notice] = 'Product was successfully deleted.'
    else
      flash[:alert] = 'Product was not deleted.'
    end
  end

  def search
    index
    render :index
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :description, images: [])
  end
end

app/views/products/_form.html.erb
<div class="panel-body">
  <%= form_with model: product,local: true do |form| %>
    <%= render 'shared/error_messages',resource: product %>
    <div class="field form-group">
      <br>
      <%= form.text_field :name, autocomplete: "name", class: "form-control", placeholder: "Name" %>
    </div>

    <div class="field form-group">
      <br />
      <%= form.number_field :price, autocomplete: "price", class: "form-control", placeholder: "Price" %>
    </div>

    <div class="field form-group">
      <br>
      <%= form.text_field :description, autocomplete: "description", class: "form-control", placeholder: "Description" %>
    </div>

    <div class="field form-group">
      <br>
      <%= form.file_field :images, multiple: true %>
    </div>

    <div class="actions">
      <br>
      <%= form.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Edit Product</h4>
  </div>
  <%= render 'form', product: @product %>
</div>
<%= link_to 'Show', @product, class: "btn btn-info" %>

app/views/products/index.html.erb
<h1>Products</h1>

<% @products.each do |product| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><strong><%= product.name %></strong></h3>
    </div>
    <div class="panel-body">
      <strong>Price: </strong>
      <%= number_to_currency(product.price) %>
      <br><br>
      <strong>Description: </strong>
      <%= product.description %>
      
      <% if product.images.count > 0 %>
        <br><br>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <% (product.images.count).times do |i| %>
            <li data-target="#carousel-example-generic" data-slide-to="<% i %>" class="active"></li>
          <% end %>
        </ol>
        <div class="carousel-inner" role="listbox">
          <% counter=1 %>
          <% (0...product.images.count).each do |image| %>
            <% if counter == 1%>
              <div class="item active">
                <%= image_tag(product.images[image]) %>
                <div class="carousel-caption">
                </div>
              </div>
            <% else %>
              <div class="item">
                <%= image_tag(product.images[image]) %>
                <div class="carousel-caption">
                </div>
              </div>
            <% end %>
            <% counter = counter + 1 %>
          <% end %>
        </div>
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <% end %>

    <br><br>
      <% if user_signed_in? %>
        <div class="btn-group">
          <div style="display:flex">
            <div>
              <%= link_to "Show Product", product, class: "btn btn-primary" %>
            </div>
            <% if product.user_id != current_user.id %>
              <div style="margin-left:5px">
                <%= button_to "Add to cart", cart_items_path(:product_id => product.id), remote: true, class: "btn btn-success" %>  
              </div>
            <% end %>
            <% if product.user_id == current_user.id %>
              <div style="margin-left:5px">
                <%= link_to "Edit Product", edit_product_path(product), class: "btn btn-info" %>
              </div>
              <div style="margin-left:5px">
                <%= link_to "Delete Product", product, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
              </div>
            <% end %>
          </div>
        </div>
      <% else %>
        <%= button_to "Add to cart", cart_items_path(:product_id => product.id), remote: true, class: "btn btn-success" %> 
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Add New Product</h4>
  </div>
  <div class="panel-body">
    <%= form_with model: @product, local: true do |form| %>

    <div class="field form-group">
      <br>
      <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "Name" %>
    </div>

    <div class="field form-group">
      <br />
      <%= form.number_field :price, autofocus: true, autocomplete: "price", class: "form-control", placeholder: "Price" %>
    </div>

    <div class="field form-group">
      <br>
      <%= form.file_field :images, multiple: true %>
    </div>

    <div class="actions">
      <%= form.submit "Create Product", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong><%= @product.name %></strong></h3>
  </div>
  <div class="panel-body">
    <strong>Price: </strong>
    <%= number_to_currency(@product.price) %>
    <br><br>
    <strong>Description: </strong>
    <%= @product.description %>
      
      <% if @product.images.count > 0 %>
        <br><br>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <% (@product.images.count).times do |i| %>
            <li data-target="#carousel-example-generic" data-slide-to="<% i %>" class="active"></li>
          <% end %>
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <% counter=1 %>
          <% (0...@product.images.count).each do |image| %>
            <% if counter == 1%>
              <div class="item active">
                <%= image_tag(@product.images[image]) %>
                <div class="carousel-caption">
                </div>
              </div>
            <% else %>
              <div class="item">
                <%= image_tag(@product.images[image]) %>
                <div class="carousel-caption">
                </div>
              </div>
            <% end %>
            <% counter = counter + 1 %>
          <% end %>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <% end %>
    <br><br>
    <div class="btn-group">
      <div style="display:flex">
        <% if @product.user_id != current_user.id %>
          <div>
            <%= button_to "Add to cart", cart_items_path(:product_id => @product.id), remote: true, class: "btn btn-success" %>  
          </div>
        <% end %>
        <% if @product.user_id == current_user.id %>
          <div style="margin-left:5px">
            <%= link_to "Edit Product", edit_product_path(@product), class: "btn btn-info" %>
          </div>
          <div style="margin-left:5px">
            <%= link_to "Delete Product", @product, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
    <br><br>
    <div id="comment_pane">
      <% @comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
    </div>
    <div>
    <% if @product.user_id != current_user.id %>
      <%= render 'comments/form' %>
    <% end %>
    </div>
  </div>
</div>